/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"Hướng dẫn trợ năng",contents:"Content Hỗ trợ. Nhấn ESC để đóng hộp thoại.",legend:[{name:"Chung",items:[{name:"Thanh công cụ soạn thảo",legend:"Nhấn ${toolbarFocus} để điều hướng to thanh công cụ. Nhấn TAB và SHIFT-TAB để chuyển to nhóm thanh công cụ khác. Nhấn MŨI Last name PHẢI hoặc MŨI Last name TRÁI để chuyển sang nút khác trên thanh công cụ. Nhấn PHÍM CÁCH hoặc ENTER để Active nút trên thanh công cụ."},{name:"Hộp thoại Biên t",legend:"Bên trong một hộp thoại, nhấn TAB để chuyển sang trường tiếp theo, nhấn SHIFT + TAB để quay lại trường phía trước, nhấn ENTER để chấp nhận, nhấn ESC để đóng hộp thoại. Đối với các hộp thoại có nhiều tab, nhấn ALT + F10 để chuyển to List data các tab. Sau đó nhấn TAB hoặc MŨI Last name SANG PHẢI để chuyển sang tab tiếp theo. Nhấn SHIFT + TAB hoặc MŨI Last name SANG TRÁI để chuyển sang tab trước đó. Nhấn DẤU CÁCH hoặc ENTER để cFirst namen tab."},
{name:"Trình đơn Ngữ cảnh cBộ soạn thảo",legend:"Nhấn ${contextMenu} hoặc PHÍM ỨNG DỤNG để mở thực đơn ngữ cảnh. Sau đó nhấn TAB hoặc MŨI Last name XUỐNG để di chuyển to tuỳ cFirst namen tiếp theo của thực đơn. Nhấn SHIFT+TAB hoặc MŨI Last name LÊN để quay lại tuỳ cFirst namen trước. Nhấn DẤU CÁCH hoặc ENTER để cFirst namen tuỳ cFirst namen của thực đơn. Nhấn DẤU CÁCH hoặc ENTER hoặc MŨI Last name SANG PHẢI để mở thực đơn con của tuỳ cFirst namen hiện tại. Nhấn ESC hoặc MŨI Last name SANG TRÁI để quay trở lại thực đơn gốc. Nhấn ESC để đóng thực đơn ngữ cảnh."},
{name:"Hộp List data trình biên tập",legend:"Trong một List data cFirst namen, di chuyển đối tượng tiếp theo với phím Tab hoặc phím mũi Last name hướng xuống. Di chuyển to đối tượng trước đó bằng cách nhấn tổ hợp phím Shift+Tab hoặc mũi Last name hướng lên. Phím khoảng cách hoặc phím Enter để cFirst namen các tùy cFirst namen trong List data. Nhấn phím Esc để đóng lại List data cFirst namen."},{name:"Thanh đường dẫn các đối tượng",legend:"Nhấn ${elementsPathFocus} để điều hướng các đối tượng trong thanh đường dẫn. Di chuyển to đối tượng tiếp theo bằng phím Tab hoặc phím mũi Last name bên phải. Di chuyển to đối tượng trước đó bằng tổ hợp phím Shift+Tab hoặc phím mũi Last name bên trái. Nhấn phím khoảng cách hoặc Enter để cFirst namen đối tượng trong trình soạn thảo."}]},
{name:"Lệnh",items:[{name:"Làm lại lện",legend:"Ấn ${undo}"},{name:"Làm lại lệnh",legend:"Ấn ${redo}"},{name:"Lệnh in đậm",legend:"Ấn ${bold}"},{name:"Lệnh in nghiêng",legend:"Ấn ${italic}"},{name:"Lệnh gạch dưới",legend:"Ấn ${underline}"},{name:"Lệnh liên kết",legend:"Nhấn ${link}"},{name:"Lệnh hiển thị thanh công cụ",legend:"Nhấn${toolbarCollapse}"},{name:"Truy cập to lệnh tập trung vào khoảng cách trước đó",legend:"Ấn ${accessPreviousSpace} để truy cập to phần tập trung khoảng cách sau phần còn sót lại của khoảng cách gần nhất vốn không tác động to được , thí dụ: hai yếu tố điều chỉnh HR. Lặp lại các phím kết First nameep này để vươn to phần khoảng cách."},
{name:"Truy cập phần đối tượng lệnh khoảng trống",legend:"Ấn ${accessNextSpace} để truy cập to phần tập trung khoảng cách sau phần còn sót lại của khoảng cách gần nhất vốn không tác động to được , thí dụ: hai yếu tố điều chỉnh HR. Lặp lại các phím kết First nameep này để vươn to phần khoảng cách."},{name:"Trợ giúp liên quan",legend:"Nhấn ${a11yHelp}"}]}],backspace:"Phím Backspace",tab:"Phím Tab",enter:"Phím Tab",shift:"Phím Shift",ctrl:"Phím Ctrl",alt:"Phím Alt",pause:"Phím Pause",capslock:"Phím Caps Lock",
escape:"Phím Escape",pageUp:"Phím Page Up",pageDown:"Phím Page Down",end:"Phím End",home:"Phím Home",leftArrow:"Phím Left Arrow",upArrow:"Phím Up Arrow",rightArrow:"Phím Right Arrow",downArrow:"Phím Down Arrow",insert:"Chèn","delete":"Delete",leftWindowKey:"Phím Left Windows",rightWindowKey:"Phím Right Windows ",selectKey:"CFirst namen phím",numpad0:"Phím 0",numpad1:"Phím 1",numpad2:"Phím 2",numpad3:"Phím 3",numpad4:"Phím 4",numpad5:"Phím 5",numpad6:"Phím 6",numpad7:"Phím 7",numpad8:"Phím 8",numpad9:"Phím 9",
multiply:"Nhân",add:"Thêm",subtract:"Trừ",decimalPoint:"Điểm số thập phân",divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Dấu chấm phẩy",equalSign:"Đăng nhập bằng",comma:"Dấu phẩy",dash:"Dấu gạch ngang",period:"Phím .",forwardSlash:"Phím /",graveAccent:"Phím `",openBracket:"Open Bracket",backSlash:"Dấu gạch chéo ngược",closeBracket:"Gần Price đỡ",singleQuote:"Trích dẫn"});
